### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by pr0fsmith** [cobalamin/obsidian-remarkable#1]
How about creating a script that takes a screenshot and creates a .md file based on some user input and stores it in a folder.  Someone could then sync this folder with a folder on their pc with say nextcloud or another cloud service so the screenshot would be accessible.  This would be great as I like to take notes and quotes from books I'm reading and this feature would allow me to connect my Obsidian notes to my reading notes and annotations easily.

**Comment by cobalamin** [comment]
Hi there! Sorry, but I don't fully understand your suggestion. Is what you're asking not possible with the abilities of this plugin as it is? I'm imagining this:

- Put your entire Obsidian Vault into a cloud-synced folder (Dropbox / Nextcloud / ...)
- Create a new note (.md file), possibly from a template
- Use the command/shortcut to insert a rM drawing into the note
- Now the note and the screenshot file are both synced via your cloud service.

If I misunderstood you, please elaborate further.

**Comment by pr0fsmith** [comment]
What you're saying makes sense.  After giving it some more thought, you're making more sense than what I'm saying.  Since I couldn't get resnap working I went a different direction with being able to take screenshots but I'm going try to use your post processing script in the solution I found.  It would be great though if I could manually crop the image so I can crop out portions of the picture (like text from a page of a book).

**Comment by cobalamin** [comment]
For that purpose, you could build an extended Python postprocessing script that launches some GUI for cropping the image and overwrites the input image with its cropped version when you close that GUI. Or use any other scripting language or executable as a post-processing step, whatever makes this workflow easiest.
