### ISSUE TITLE
Installing PIL

### ISSUE THREAD

**Issue by pr0fsmith** [cobalamin/obsidian-remarkable#2]
I can't seem to figure out how to install Pillow.  pip says that libjpeg headers are they are not offered in entware.  I've attempted 'opkg install libjpeg-dev' without success.

**Comment by cobalamin** [comment]
You should install Pillow on your computer, not on the reMarkable – the postprocessing script will run on the PC. Maybe I should make that more clear in the docs.

**Comment by pr0fsmith** [comment]
Thanks for the clarification.  I was just one step away from getting it working too.  OK I will set up the post processing to happen on my server then. Thanks again.
