### ISSUE TITLE
Installing?

### ISSUE THREAD

**Issue by axfelix** [cobalamin/obsidian-remarkable#3]
Hi,

Could you make it a bit clearer in the readme how you're supposed to sideload an Obsidian plugin? I've gotten this far but I can't seem to get it to enable:

![image](https://user-images.githubusercontent.com/252047/129636414-d5098ec6-1545-4284-91f1-a181deaf9d85.png)

**Comment by Draic** [comment]
seems this project is DOA unfortunately

**Comment by boomskats** [comment]
My PR #4 from last week should bring it back to life. Install instructions using BRAT updated in readme in the PR

**Comment by cobalamin** [comment]
Thanks @boemska-nik, I merged the PR and added a new release based on it. Closing this now
