### ISSUE TITLE
Install issue with BRAT?

### ISSUE THREAD

**Issue by Folcon** [cobalamin/obsidian-remarkable#6]
<img width="294" alt="image" src="https://user-images.githubusercontent.com/123055/168191076-739fa52b-5863-4a7d-899c-55c4747cbbbe.png">

**Comment by Folcon** [comment]
I've manually installed it, but there are still issues:
```
VM149:29 Uncaught (in promise) Nonzero exitcode.
STDERR: /Users/folcon/.local/bin/reSnap.sh: line 163: ffmpeg: command not found
/Users/folcon/.local/bin/reSnap.sh: line 162: lz4: command not found
```

Once I amended reSnap to specify absolute paths for the above, this happened:
```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'replaceRange')
    at MyPlugin.eval (eval at <anonymous> (app.js:1:1), <anonymous>:5845:24)
    at Generator.next (<anonymous>)
    at fulfilled (eval at <anonymous> (app.js:1:1), <anonymous>:28:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

The thing is, I can call reSnap.sh from the command line and it works, so that's not the problem.

~~I've also managed to successfully call the js functions from node in the command line, so not sure where the specific issue is. I don't have time to debug this further at the moment.~~

I've created a PR that fixes the ffmpeg and lz4 issues (https://github.com/cloudsftp/reSnap/pull/6).

I've also got a WIP pull here (https://github.com/Folcon/obsidian-remarkable/pull/1), I've still not pinned down why the file doesn't get written.

I don't have time to debug this further at the moment.

Ok, so that got merged into [cloudsftp/reSnap](https://github.com/cloudsftp/reSnap/commit/ba17caf75da1d033f6ee95d6fbd1527f90bc7098).

**Comment by boomskats** [comment]
I think the release/tags need to be updated in this repo. I'm not sure if I can do it, but I did it a couple of months ago on my own fork of this before I put in the PR. 

@Folcon if you try to BRAT install it from boemska-nik/obsidian-remarkable does it work? Tagged release [here](https://github.com/boemska-nik/obsidian-remarkable/releases/tag/1.1.0)

**Comment by Folcon** [comment]
@boemska-nik, just gave this a quick go and I got this:
```javascript
Uncaught (in promise) Nonzero exitcode.
STDERR: 
STDOUT: head not found on reMarkable 2.0. Please refer to the README
```

That's not to say your branch doesn't work, I need to properly debug it to work out where the problem is =)...

**Comment by cobalamin** [comment]
I added a tagged release for the merged PR from you - thanks @boemska-nik!

I'm not sure if/how the problem in your last comment is related to this repo at all @Folcon; this seems to be on reSnap's side or your device's?

**Comment by boomskats** [comment]
@Folcon take a look at the reSnap readme, specifically [this part](https://github.com/cloudsftp/reSnap#installing-programs-on-your-remarkable). You're missing the pre-requisites on your rm2 which you'll need to install using toltec.
